#!/bin/sh

# Loading the modules needed by my app:
#modprobe xxxxx
 
# Launching my app:

export SDL_NOMOUSE=1
/usr/bin/chocolate-doom &          # <-- Don't forget the "&" otherwise other system stuff won't start until you leave your app !!!

exit 0
